{% set name = "aiohttp-graphql" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29035589ca0929f5dc19b09461db0a2563db0166a6efcf22e23498a44e45040e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - aiohttp >=3,<4
    - graphql-core >=2.0,<3
    - graphql-server-core >=1.2,<2
    - python

test:
  imports:
    - aiohttp_graphql

about:
  home: https://github.com/graphql-python/aiohttp-graphql
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Adds GraphQL support to your aiohttp application
  doc_url: https://github.com/graphql-python/aiohttp-graphql
  dev_url: https://github.com/graphql-python/aiohttp-graphql

extra:
  recipe-maintainers:
    - KingDarBoja
