travis:
  secure:
    BINSTAR_TOKEN: DF+b0Qo7rZP7nAy4nmRSNBQ27rELMRRcM/dMrKvV6EdHGdo+A1q5JtwdxLR5Yg8ywiF82G4zt2j428TnEcWNKFX1cMhyg9zRD0Jgnas4jM/K2DN0tZa1+ozz9eq///pSuMca30bUJHoRfIT2tJdkBAO6P3RbLP9CGBZxdh3EdN/7qL9iyYxMojdFLZumRmRT/QVeYWWh8wJOJlm1RvAcw/mHd91zFMy9LS9gMB4tCqtBogOXvCHrCIKt7V+8d5KWGOptTiF/lxCiQ2bXzwk4k6Waas25h5ZHTn44slJOVXLqx1JeP5BEsUC9EXB1JdWoNGzQLEBCQN7l2Ncw+LxiZToJAPNRjHHg4ZFWUoC2shzline/9eXb549Dq89sLiq4+AXBGfXlC1PbAdsLAmFFTbz/XEQLWG7W4GyHBtJ7G2zRq4FsJRIsN05PARZSKlTF5CK+9Hz3pT17eBPGHVte1BQ+xFxJpmeXrGG1M53qO7/tlKWolUZY4gl6zISvryjTit+9BpvU0jzrew5mk3fOZHnMjdTkNL1lTgzsqIans9PTzB4u9m7jEir3Fwf8BYyrJZpUO9QPWsSh18NLHvQmE8DRuBQ4UT2HY34lsuJDOr2XdwNvQhXZiaXZyarVINm1eOARTs1czJBFgdql3QJbL72Jko5Qm5B28RgWCXmejRE=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
